name: CI

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  build:
    name: "[DEV] Build Frontend"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v2

      - name: "[FE] Install Dependencies"
        run: yarn

      - name: "[FE] Run Tests"
        run: yarn test

      - name: "[FE] Build React App"
        run: yarn build
